// Regenerates src/abis from the compiled contracts, as typed constants.
//
// The contracts live in a separate repository; this script expects their
// build output at ../contracts/out (the layout used when this package is
// checked out inside that repository). Consumers of the SDK never need it.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = join(here, "..", "..", "contracts", "out");
const target = join(here, "..", "src", "abis");

const contracts = [
  { name: "BotInstanceNFT", file: "botInstanceNft", symbol: "botInstanceNftAbi" },
  { name: "TradeExecutor", file: "tradeExecutor", symbol: "tradeExecutorAbi" },
];

for (const { name, file, symbol } of contracts) {
  const artifact = JSON.parse(readFileSync(join(contractsOut, `${name}.sol`, `${name}.json`), "utf8"));
  const body =
    `// Generated by scripts/sync-abis.mjs from the compiled contracts — do not edit by hand.\n` +
    `export const ${symbol} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(target, `${file}.ts`), body);
  console.log(`${name}: ${artifact.abi.length} entries → src/abis/${file}.ts`);
}
